const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b",
    },
    price: 1500,
    location: "Malibu",
    country: "United States",
    category: ["Beach", "Romantic", "Rooms"],
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    },
    price: 1200,
    location: "New York City",
    country: "United States",
    category: ["Iconic Cities", "Rooms", "Hotel"],
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d",
    },
    price: 1000,
    location: "Aspen",
    country: "United States",
    category: ["Mountain", "Camping", "Lakefront"],
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany in this beautifully restored villa.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945",
    },
    price: 2500,
    location: "Florence",
    country: "Italy",
    category: ["Iconic Cities", "Luxiary", "Romantic"],
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the treetops in this unique treehouse retreat.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4",
    },
    price: 800,
    location: "Portland",
    country: "United States",
    category: ["Camping", "Farms", "Mountain"],
  },
  {
    title: "Beachfront Paradise",
    description: "Step out of your door onto the sandy beach.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9",
    },
    price: 2000,
    location: "Cancun",
    country: "Mexico",
    category: ["Beach", "Amazing Pools", "Hotel"],
  },
  {
    title: "Rustic Cabin by the Lake",
    description: "Spend your days fishing and kayaking on the serene lake.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b",
    },
    price: 900,
    location: "Lake Tahoe",
    country: "United States",
    category: ["Lakefront", "Camping", "Mountain"],
  },
  {
    title: "Luxury Penthouse with City Views",
    description: "Indulge in luxury living with panoramic city views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd",
    },
    price: 3500,
    location: "Los Angeles",
    country: "United States",
    category: ["Luxiary", "Iconic Cities", "Hotel"],
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description: "Hit the slopes right from your doorstep.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb",
    },
    price: 3000,
    location: "Verbier",
    country: "Switzerland",
    category: ["Mountain", "Luxiary", "Camping"],
  },
  {
    title: "Historic Castle in Scotland",
    description: "Live like royalty in this historic castle.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98",
    },
    price: 4000,
    location: "Scottish Highlands",
    country: "United Kingdom",
    category: ["Castles", "Mountain", "Romantic"],
  },
  {
    title: "Luxury Villa in the Maldives",
    description: "Indulge in luxury in this overwater villa.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1439066615861-d1af74d74000",
    },
    price: 6000,
    location: "Maldives",
    country: "Maldives",
    category: ["Luxiary", "Amazing Pools", "Beach", "Romantic"],
  },
  {
    title: "Lakefront Cabin in New Hampshire",
    description: "Spend your days by the lake in this cozy cabin.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1578645510447-e20b4311e3ce",
    },
    price: 1200,
    location: "New Hampshire",
    country: "United States",
    category: ["Lakefront", "Camping", "Mountain"],
  },
  {
  title: "Beachside Villa in Goa",
  description: "Wake up to ocean views in this luxurious beach villa.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
  },
  price: 3500,
  location: "Goa",
  country: "India",
  category: ["Beach", "Luxury"],
},
{
  title: "Hilltop Cottage in Manali",
  description: "A peaceful cottage with stunning mountain views.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
  },
  price: 1800,
  location: "Manali",
  country: "India",
  category: ["Mountain", "Nature"],
},
{
  title: "Desert Camp in Jaisalmer",
  description: "Experience royal desert life under the stars.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
  },
  price: 2200,
  location: "Jaisalmer",
  country: "India",
  category: ["Camping", "Desert"],
},
{
  title: "Forest Treehouse in Kerala",
  description: "Live among nature in a beautiful treehouse.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
  },
  price: 2600,
  location: "Wayanad",
  country: "India",
  category: ["Forest", "Nature"],
},
{
  title: "Luxury Apartment in New York",
  description: "Modern apartment in the heart of the city.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1494526585095-c41746248156",
  },
  price: 5000,
  location: "New York",
  country: "United States",
  category: ["City", "Luxury"],
},
{
  title: "Snow Cabin in Alaska",
  description: "Cozy cabin surrounded by snow-covered landscapes.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1482192596544-9eb780fc7f66",
  },
  price: 2800,
  location: "Alaska",
  country: "United States",
  category: ["Snow", "Mountain"],
},
{
  title: "Lake House in Udaipur",
  description: "Romantic lake-view house near royal palaces.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1521401292936-0a2129a30b1c",
  },
  price: 3000,
  location: "Udaipur",
  country: "India",
  category: ["Lakefront", "Heritage"],
},
{
  title: "Countryside Farmhouse",
  description: "Relax in a quiet farmhouse surrounded by fields.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
  },
  price: 1500,
  location: "Punjab",
  country: "India",
  category: ["Farm", "Nature"],
},
{
  title: "Island Bungalow in Maldives",
  description: "Private island stay with crystal clear waters.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21",
  },
  price: 8000,
  location: "Malé",
  country: "Maldives",
  category: ["Beach", "Luxury"],
},
{
  title: "Heritage Haveli in Jaipur",
  description: "Live royal life in a traditional haveli.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
  },
  price: 2700,
  location: "Jaipur",
  country: "India",
  category: ["Heritage", "City"],
},
{
  title: "Jungle Lodge in Jim Corbett",
  description: "Wildlife stay near the national park.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429",
  },
  price: 2400,
  location: "Uttarakhand",
  country: "India",
  category: ["Forest", "Wildlife"],
},
{
  title: "Studio Apartment in Tokyo",
  description: "Compact and modern living in Tokyo city.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
  },
  price: 4200,
  location: "Tokyo",
  country: "Japan",
  category: ["City", "Modern"],
},
{
  title: "Mountain Chalet in Switzerland",
  description: "Luxury chalet with snow-capped mountain views.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1519681393784-d120267933ba",
  },
  price: 6500,
  location: "Zermatt",
  country: "Switzerland",
  category: ["Mountain", "Luxury"],
},
{
  title: "Riverside Cottage in Rishikesh",
  description: "Peaceful stay beside the holy river Ganga.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
  },
  price: 1600,
  location: "Rishikesh",
  country: "India",
  category: ["Riverfront", "Spiritual"],
},
{
  title: "Modern Villa in Dubai",
  description: "High-end villa with private pool.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1494526585095-c41746248156",
  },
  price: 7000,
  location: "Dubai",
  country: "UAE",
  category: ["Luxury", "City"],
},
{
  title: "Eco Lodge in Sikkim",
  description: "Sustainable stay amidst Himalayan beauty.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
  },
  price: 1900,
  location: "Sikkim",
  country: "India",
  category: ["Eco", "Mountain"],
},
{
  title: "Cliff House in Ireland",
  description: "Dramatic ocean views from cliffside home.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
  },
  price: 3600,
  location: "Cliffs of Moher",
  country: "Ireland",
  category: ["Ocean", "Luxury"],
},
{
  title: "Backwater Villa in Alleppey",
  description: "Stay near serene Kerala backwaters.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
  },
  price: 2500,
  location: "Alleppey",
  country: "India",
  category: ["Lakefront", "Nature"],
},
{
  title: "Countryside Barn in England",
  description: "Rustic barn stay with modern comforts.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
  },
  price: 2300,
  location: "Cotswolds",
  country: "United Kingdom",
  category: ["Countryside", "Rustic"],
},
{
  title: "Island Hut in Bali",
  description: "Traditional hut surrounded by greenery.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21",
  },
  price: 2100,
  location: "Bali",
  country: "Indonesia",
  category: ["Island", "Nature"],
}

];

module.exports = { data: sampleListings };
